<?php
return array(
    1 => array(
        'id' => 'w001',
        'name' => 'Rusty Sword',
        'type' => 'Sword',
        'attack1Name' => 'Slash',
        'attack2Name' => 'Stab',
        'attack1Damage' => 25,
        'attack2Damage' => 20,
        'price' => 0,
    ),
    2 => array(
        'id' => 'w002',
        'name' => 'Buster Sword',
        'type' => 'Greatsword',
        'attack1Name' => 'Hack and Slash',
        'attack2Name' => 'Protrude',
        'attack1Damage' => 40,
        'attack2Damage' => 30,
        'price' => 100,
    ),
    3 => array(
        'id' => 'w003',
        'name' => 'Severance',
        'type' => 'Katana',
        'attack1Name' => 'Blood Slash',
        'attack2Name' => 'Sweeping Edge',
        'attack1Damage' => 35,
        'attack2Damage' => 23,
        'price' => 70,
    ),
    4 => array(
        'id' => 'w004',
        'name' => 'Pirate Mark',
        'type' => 'Cutlass',
        'attack1Name' => 'Plundering Cut',
        'attack2Name' => 'Water Wake',
        'attack1Damage' => 27,
        'attack2Damage' => 23,
        'price' => 50,
    ),
    5 => array(
        'id' => 'w005',
        'name' => 'King Alant Greatsword',
        'type' => 'Greatsword',
        'attack1Name' => 'Pulsing Strike',
        'attack2Name' => 'Bury em in Gold',
        'attack1Damage' => 50,
        'attack2Damage' => 60,
        'price' => 500,
    ),
);