<?php
$quoteArray = [
    "Seek the veiled moon, and you shall see the truth.",
    "The blood remembers what the mind forgets.",
    "We are but echoes in a city of ash.",
    "Eyes... eyes where there should be none.",
    "The dream does not end. Only you do.",
    "He begged the stars for mercy. They answered in teeth.",
    "What is insight, if not the burden of knowing?",
    "They locked the gates too late. It was already inside.",
    "The choir sings in silence now.",
    "Blood is sacred, but not pure.",
    "A great beast stirs beneath the chapel.",
    "Those who looked up were the first to fall.",
    "The candles still burn. Who lit them?",
    "Her laughter echoes through the bone halls.",
    "The old blood blooms in flesh.",
    "You must forget to remember.",
    "One by one, they knelt before the writhing sky.",
    "We fed it prayers. It fed us nightmares.",
    "Sanity is a luxury few afford down here.",
    "He drank deeply, and wept backwards.",
    "There are no mirrors here for a reason.",
    "The bells ring at dusk. Never answer them.",
    "We caged the beast. It taught us words.",
    "This city is a womb and a tomb.",
    "The ink bled from the pages. They screamed.",
    "We hunted the curse until we became it.",
    "They grew eyes to see the gods. Then tore them out.",
    "Madness is not the end. It is the beginning.",
    "Even the statues whisper.",
    "Behind the altar, a door that leads nowhere.",
    "The sky was wrong that night.",
    "His voice still hums in the floorboards.",
    "A child of the void sleeps beneath.",
    "It asked me to remember. I never forgot.",
    "Flesh is weak. But the song... the song is eternal.",
    "Only the blind survived the first awakening.",
    "We drank from the chalice. Now we are hollow.",
    "No graves. Only regrets.",
    "It does not bleed, but it hungers.",
    "They traded their bones for blessings.",
    "We buried the sun in the catacombs.",
    "The key was never meant to be found.",
    "Do not look behind the veil. It looks back.",
    "They speak of ascension. All I see is rot.",
    "Even the crows won't eat here.",
    "He gave his name to the dark.",
    "The hunter is the hunted now.",
    "They stitched together gods. And prayed.",
    "Your footsteps echo louder here.",
    "Not all who sleep beneath the crypt are dead.",
];

$randomNumber = rand(0,49);
$randomQuote = $quoteArray[$randomNumber];

return $randomQuote;